<x-app-layout title="View Report">
    <div class="container-fluid px-4 py-4">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div>
                <h1 class="mb-1 h3 fw-bold">{{ $report->report_name }}</h1>
                <p class="text-muted mb-0">Details of the financial report</p>
            </div>
            <div class="d-flex gap-2">
                <a href="{{ route('bursar.reports.download', $report->id) }}" class="btn btn-outline-primary">
                    <i class="fas fa-download me-1"></i> Download
                </a>
                <a href="{{ route('bursar.reports.index') }}" class="btn btn-outline-secondary">
                    <i class="fas fa-arrow-left me-1"></i> Back to Reports
                </a>
            </div>
        </div>

        <div class="card shadow-sm">
            <div class="card-body">
                <div class="row g-3">
                    <div class="col-md-6">
                        <h6 class="text-muted">Report Type</h6>
                        <p>{{ ucfirst($report->report_type) }}</p>
                    </div>
                    <div class="col-md-6">
                        <h6 class="text-muted">Generated By</h6>
                        <p>{{ $report->generatedBy->name }}</p>
                    </div>
                    <div class="col-md-6">
                        <h6 class="text-muted">Start Date</h6>
                        <p>{{ $report->start_date->format('M d, Y') }}</p>
                    </div>
                    <div class="col-md-6">
                        <h6 class="text-muted">End Date</h6>
                        <p>{{ $report->end_date->format('M d, Y') }}</p>
                    </div>
                    <div class="col-12">
                        <h6 class="text-muted">Generated On</h6>
                        <p>{{ $report->created_at->format('M d, Y H:i') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('styles')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    @endpush
    @push('scripts')
        <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
        @if(session('success'))
            <script>
                Toastify({
                    text: "{{ session('success') }}",
                    duration: 3000,
                    backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)"
                }).showToast();
            </script>
        @endif
        @if(session('error'))
            <script>
                Toastify({
                    text: "{{ session('error') }}",
                    duration: 3000,
                    backgroundColor: "linear-gradient(to right, #ff5f6d, #ffc371)"
                }).showToast();
            </script>
        @endif
    @endpush
</x-app-layout>
